/**
 * GameHub-TV Official Google Play Store Games Catalog
 * Authentic Android games with real Google Play Store URLs, package IDs, controller layouts, and 60 FPS profile configs.
 */

import { GameMetadata } from '../types/models';

export const INITIAL_GAMES: GameMetadata[] = [
  {
    id: 'roblox',
    title: 'Roblox',
    category: 'Sandboxes',
    packageName: 'com.roblox.client',
    developer: 'Roblox Corporation',
    tagline: 'Infinite virtual universe of community-created 3D experiences',
    description:
      'Explore millions of immersive 3D worlds created by a global community. From adventure and roleplay to obstacle courses and tycoons, processed natively on your Android phone and projected directly to your TV in crisp 1080p 60 FPS.',
    heroImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1550745165-9bc0b252726f?auto=format&fit=crop&w=800&q=80',
    rating: 'Teen (10+)',
    releaseYear: 2006,
    tags: ['Sandbox', 'Multiplayer', 'Cross-Platform', 'Creator Worlds'],
    minAndroidVersion: 8,
    minRamGb: 4,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.roblox.client',
    controllerMapping: {
      profileName: 'Roblox Virtual & Gamepad Hybrid',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Jump',
        bButton: 'Interact',
        xButton: 'Action / Use Tool',
        yButton: 'Backpack / Inventory',
        triggers: 'RT: Zoom / LT: Reset Cam',
        dpad: 'Navigate Toolbar Item',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 12000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'minecraft',
    title: 'Minecraft',
    category: 'Adventure',
    packageName: 'com.mojang.minecraftpe',
    developer: 'Mojang Studios',
    tagline: 'Build, explore, and survive in boundless infinite block worlds',
    description:
      'Explore infinite worlds and build everything from the simplest of homes to the grandest of castles. Play in creative mode with unlimited resources or mine deep into the world in survival mode, crafting weapons and armor to fend off dangerous mobs.',
    heroImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1518709268805-4e9042af9f23?auto=format&fit=crop&w=800&q=80',
    rating: 'Everyone 10+',
    releaseYear: 2011,
    tags: ['Survival', 'Crafting', 'Open World', 'Co-op', 'Creative'],
    minAndroidVersion: 9,
    minRamGb: 4,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.mojang.minecraftpe',
    controllerMapping: {
      profileName: 'Standard Dual-Stick Console Profile',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Jump / Swim',
        bButton: 'Sneak / Dismount',
        xButton: 'Open Crafting Menu',
        yButton: 'Open Inventory',
        triggers: 'RT: Attack / Mine • LT: Place Block',
        dpad: 'Cycle Hotbar Quick Slots',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 15000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'codm',
    title: 'Call of Duty: Mobile',
    category: 'Action',
    packageName: 'com.activision.callofduty.shooter',
    developer: 'Activision Publishing, Inc.',
    tagline: 'Console-quality FPS action, multiplayer maps & battle royale',
    description:
      'Experience iconic multiplayer maps and fan-favorite modes anytime. 100-player Battle Royale battleground, fast 5v5 team deathmatch, and Sniper vs sniper battle. Optimized for GameHub TV with high dynamic range and low-latency input.',
    heroImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    rating: 'Mature 17+',
    releaseYear: 2019,
    tags: ['FPS', 'Multiplayer', 'Competitive', 'Tactical', 'Battle Royale'],
    minAndroidVersion: 9,
    minRamGb: 6,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.activision.callofduty.shooter',
    controllerMapping: {
      profileName: 'Tactical FPS Shooter Profile',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Jump / Slide',
        bButton: 'Crouch / Prone',
        xButton: 'Reload Ammo',
        yButton: 'Swap Primary / Secondary Weapon',
        triggers: 'RT: Fire Weapon • LT: Aim Down Sights (ADS)',
        dpad: 'Activate Scorestreaks & Operator Skill',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 18000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'freefire',
    title: 'Garena Free Fire MAX',
    category: 'Battle Royale',
    packageName: 'com.dts.freefiremax',
    developer: 'Garena International I',
    tagline: 'Premium battle royale experience with Ultra HD visuals',
    description:
      'Designed exclusively to deliver premium gameplay in Battle Royale. Enjoy a variety of exciting combat modes with all Free Fire players via exclusive Firelink technology with silky 60 FPS projection.',
    heroImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    rating: 'Mature 17+',
    releaseYear: 2021,
    tags: ['Battle Royale', 'Shooter', 'Multiplayer', 'Fast-Paced Action'],
    minAndroidVersion: 8,
    minRamGb: 6,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.dts.freefiremax',
    controllerMapping: {
      profileName: 'FPS Precision Layout & Gyro Aiming',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      supportsMotionSteering: true,
      buttonHints: {
        aButton: 'Jump / Vault Obstacle',
        bButton: 'Crouch / Slide',
        xButton: 'Reload Magazine',
        yButton: 'Switch Weapon',
        triggers: 'RT: Shoot • LT: Scope In',
        dpad: 'Medkit / Grenade Quick Wheel',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 18000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'pubgmobile',
    title: 'PUBG MOBILE',
    category: 'Battle Royale',
    packageName: 'com.tencent.ig',
    developer: 'Level Infinite',
    tagline: 'The original battle royale phenomenon on mobile',
    description:
      'Extreme battles in 10-minute matches. Prepare your firearms, answer the call for battle in PUBG MOBILE, and fire at will. Parachute onto vast islands, loot weapons, and survive against 99 opponents to take the Chicken Dinner.',
    heroImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1542751371-adc38448a05e?auto=format&fit=crop&w=800&q=80',
    rating: 'Teen 16+',
    releaseYear: 2018,
    tags: ['Battle Royale', 'Survival', 'Military', 'Tactical Shooter'],
    minAndroidVersion: 9,
    minRamGb: 6,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.tencent.ig',
    controllerMapping: {
      profileName: 'Tactical Battle Royale Profile',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Jump / Climb',
        bButton: 'Crouch',
        xButton: 'Reload Weapon',
        yButton: 'Prone / Stand',
        triggers: 'RT: Fire • LT: Aim Down Sights',
        dpad: 'Item Quick Slot / Lean Left-Right',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 18000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'asphalt9',
    title: 'Asphalt Legends Unite',
    category: 'Racing',
    packageName: 'com.gameloft.android.ANMP.GloftA9HM',
    developer: 'Gameloft SE',
    tagline: 'High-octane arcade racing with hypercars and jaw-dropping tracks',
    description:
      'Tear up the asphalt across spectacular international tracks with officially licensed supercars from Ferrari, Porsche, Lamborghini, and W Motors. Phone gyroscopes act as a realistic steering wheel with zero input delay.',
    heroImage: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511919884226-fd3cad34687c?auto=format&fit=crop&w=800&q=80',
    rating: 'Everyone 10+',
    releaseYear: 2018,
    tags: ['Racing', 'Arcade', 'Hypercars', 'Motion Steering', 'Nitro'],
    minAndroidVersion: 9,
    minRamGb: 6,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.gameloft.android.ANMP.GloftA9HM',
    controllerMapping: {
      profileName: 'Steering Wheel & TouchDrive Layout',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      supportsMotionSteering: true,
      buttonHints: {
        aButton: 'Nitro Boost (Single / Shockwave)',
        bButton: 'Drift / 360 Spin',
        xButton: 'Rear View Mirror',
        yButton: 'Switch Camera Perspective',
        triggers: 'RT: Throttle Accelerate • LT: Brake / Reverse',
        dpad: 'Menu Selection',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 16000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'genshin',
    title: 'Genshin Impact',
    category: 'Adventure',
    packageName: 'com.miHoYo.GenshinImpact',
    developer: 'COGNOSPHERE PTE. LTD.',
    tagline: 'Vast open-world fantasy adventure across magical Teyvat',
    description:
      'Step into Teyvat, a vast fantasy world teeming with elemental magic and diverse characters. Experience deep combat, responsive party switching, and breathtaking anime visuals on your TV display with native controller precision.',
    heroImage: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1538481199705-c710c4e965fc?auto=format&fit=crop&w=800&q=80',
    rating: 'Teen 13+',
    releaseYear: 2020,
    tags: ['RPG', 'Open World', 'Anime', 'Elemental Combat', 'Story'],
    minAndroidVersion: 10,
    minRamGb: 8,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.miHoYo.GenshinImpact',
    controllerMapping: {
      profileName: 'Action RPG Controller Layout',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Normal Attack',
        bButton: 'Elemental Skill (E)',
        xButton: 'Sprint / Evade Dash',
        yButton: 'Elemental Burst (Q)',
        triggers: 'RT: Aim Charged Shot • LT: Shortcut Wheel',
        dpad: 'Party Member Quick-Switch 1-4',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 20000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'deadcells',
    title: 'Dead Cells',
    category: 'Action',
    packageName: 'com.playdigious.deadcells.pc',
    developer: 'Playdigious',
    tagline: 'Roguevania action-platformer with brutal, fast-paced combat',
    description:
      'Play as a failed alchemic experiment and explore the sprawling, ever-changing castle to find out what happened on this gloomy island. Interconnected world, branching paths, permanent unlocks, and adrenaline-pumping 2D sword combat.',
    heroImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1563089145-599997674d42?auto=format&fit=crop&w=800&q=80',
    rating: 'Mature 17+',
    releaseYear: 2020,
    tags: ['Roguevania', 'Platformer', 'Pixel Art', 'Controller Native'],
    minAndroidVersion: 8,
    minRamGb: 4,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.playdigious.deadcells.pc',
    controllerMapping: {
      profileName: 'Precision 2D Platformer Mapping',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Jump / Double Jump',
        bButton: 'Roll / Dodge Invincibility',
        xButton: 'Primary Weapon Strike',
        yButton: 'Secondary Weapon / Shield',
        triggers: 'L1/R1: Traps & Powers • LT/RT: Healing Flask',
        dpad: 'Movement & Climbing',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 12000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'brawlstars',
    title: 'Brawl Stars',
    category: 'Action',
    packageName: 'com.supercell.brawlstars',
    developer: 'Supercell',
    tagline: 'Fast-paced 3v3 multiplayer and battle royale combat',
    description:
      'Fast-paced 3v3 multiplayer and battle royale made for mobile! Play with friends or solo across a variety of game modes in under three minutes. Unlock and upgrade dozens of Brawlers with powerful Super abilities.',
    heroImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1511512578047-dfb367046420?auto=format&fit=crop&w=800&q=80',
    rating: 'Everyone 10+',
    releaseYear: 2018,
    tags: ['Multiplayer', 'Hero Shooter', '3v3', 'Fast Combat'],
    minAndroidVersion: 8,
    minRamGb: 4,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.supercell.brawlstars',
    controllerMapping: {
      profileName: 'Dual-Stick Arena Brawler Profile',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Main Attack',
        bButton: 'Super Ability',
        xButton: 'Gadget Activation',
        yButton: 'Hypercharge',
        triggers: 'RT: Aim Attack • LT: Aim Super',
        dpad: 'Quick Emotes',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 12000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
  {
    id: 'eafc',
    title: 'EA SPORTS FC™ Mobile Soccer',
    category: 'Sports',
    packageName: 'com.ea.gp.fifamobile',
    developer: 'ELECTRONIC ARTS',
    tagline: 'Authentic world-class football simulation on the big screen',
    description:
      'Build an Ultimate Team™ of legendary soccer stars and put them to the test. Collect Player Items from world-class talent like Jude Bellingham, Erling Haaland, and Kylian Mbappé in 1080p 60 FPS glory.',
    heroImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=1920&q=80',
    coverImage: 'https://images.unsplash.com/photo-1508098682722-e99c43a406b2?auto=format&fit=crop&w=800&q=80',
    rating: 'Everyone',
    releaseYear: 2016,
    tags: ['Sports', 'Football', 'Soccer', 'Simulation', 'Multiplayer'],
    minAndroidVersion: 9,
    minRamGb: 4,
    orientation: 'landscape',
    playStoreUrl: 'https://play.google.com/store/apps/details?id=com.ea.gp.fifamobile',
    controllerMapping: {
      profileName: 'Pro Football Gamepad Profile',
      supportsTouchOverlay: true,
      supportsBluetoothGamepad: true,
      buttonHints: {
        aButton: 'Short Pass / Ground Tackle',
        bButton: 'Shoot / Sliding Tackle',
        xButton: 'Through Ball / Pressure',
        yButton: 'Lob Pass / Goalkeeper Rush',
        triggers: 'RT: Sprint Dribble • LT: Skill Move',
        dpad: 'Tactics Attack / Defense Mentality',
      },
    },
    recommendedQuality: {
      targetResolution: '1080p',
      targetFps: 60,
      maxBitrateKbps: 16000,
      codec: 'H264',
      audioEnabled: true,
    },
    playTimeMinutes: 0,
  },
];

export const CATEGORIES = [
  'All',
  'Action',
  'Battle Royale',
  'Adventure',
  'Sandboxes',
  'Racing',
  'Sports',
] as const;
